version: "3"
services:
    mongoidb:
        image: mongo
        container_name: mongodb
        environment:
           - MONGO_INITDB_ROOT_USERNAME=root
           - MONGO_INITDB_ROOT_PASSWORD=myveiaapp
        volumes:
            - mongodb-data:/data/db
        ports:
            - 27017:27017
        restart: always
    
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=myveiaapp
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=myveiaapp
        volumes:
            - mongodb-data
        ports:
            - 8081:8081
volumes:
    mongodb-data:
